- index.html
- signin.html
- signup.html
- style/common/common.css
- style/pages/landing.css
- style/pages/signin.css
- style/style.css
- style/variable.css
PC: 1200px 이상
Tablet: 768px 이상 ~ 1199px 이하
Mobile: 375px 이상 ~ 767px 이하
375px 미만 사이즈의 디자인은 고려하지 않습니다
(이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [] 팀원의 위클리 미션 PR에 코드 리뷰를 남겼나요?
- 멘토님이 주신 공통 피드백을 반영하여 css 파일을 구조화했습니다. (variable.css, reset.css, common.css 따로 저장해두고 style.css에서 import해서 적용)
- 기존에 .content .frame에 적용했던 flex-box를 전부 grid로 바꾸었습니다. 
- 처음에 .content .frame 안에 .text와 .content-img가 같은 레벨로 존재했고, .text 안에  h1과 para가 존재했습니다. 이러한 구조로 flex-box를 만들어서 구현을 했었습니다. 그랬더니 도저히.. "랜딩 페이지 Mobile 사이즈에서 제품 소개 영역의 순서를 제목, 설명, 이미지 => 제목, 이미지, 설명 순서로 변경했나요?"라는 요구사항을 만족 시킬 수가 없었습니다. 왜냐면 order라는 속성을 사용하더라도, 같은 레벨에 있는 것들만 재배치를 할 수 있었기 때문입니다. 최대한 html 구조를 변경하지 않고 반응형 웹을 만들고자 했는데 결국 제목(h1), 이미지(content-img), 설명(para)를 전부 같은 레벨로 두고 .frame으로 묶은 뒤 frame에 grid를 적용하는 식으로 바꿀 수 밖에 없었네요.. html 구조를 건들이지 않고 할 수 있는 다른 방법이 있었을까요? …
> [조유담] week3

- index.html
- signin.html
- signup.html
- styles/index.css
- styles/reset.css
- styles/signin.css
1.
.main-text 에서 줄바꿈이 되는 부분은 어떻게 해야 할 지 이해를 잘 못해서 아직 구현하지 못했는데요ㅜㅜ 다음 주차 때 같이 해보겠습니다,,
2
메타태그를 적용했는데 적용이 안되는 것 같아요
이부분 성현멘토님께서 url로 바꾸면 될 것 같다고 하셨는데요, 찾아봐도 잘 모르겠어서 한 번 더 질문드립니다ㅠㅠ
이미지 url을 어떻게 가져오는건가요... ?? 저는 이미지를 저장해서 images폴더 안에 IMG_7248.jpg 이름으로 넣어두었는데 이 방법이 아닌걸까효...?? 이미지로 첨부하겠습니다,,! 
4. 
회원가입과 로그인페이지의 요소들이, 화면을 작게하여도 좁아지지 않고 옆으로 잘립니다 ㅜㅜ 
32px의 여백도 유지되지 않는데요 이것두 어디가 잘못된건지 잘 모르겠어서 이미지로 첨부하겠습니다.. ㅠㅡㅠ 
5.
회원가입과 로그인페이지의 규격을 작게 하였을 때
body크기는 작아지는 반면에 form크기는 400px 그대로 유지되는 것 같습니다! max-width로 설정하였는데 왜 그런 걸까요? 4번에 질문한 문제의 경우 이것과 관련이 있을까요..? 어떻게 해결해야 할까요?ㅠㅠ 
6.
처음에 반응형을 어떻게 접근해야 할 지 몰라서 한참을 손을 못 대고 있다가, 다른 분들이 flex:grid로 속성을 바꿔서 미디어쿼리를 적용하면 된다고 하셔서 그제서야 손을 댈 수 있었는데요..
footer부분도 어떻게 해야 할 지 한참 고민하다가 다른 분이 footer에도 grid속성을 사용하신 걸 보고 따라했습니다ㅠ_ㅠ
(저의 머리로는 grid로 정렬하는 방법을 생각해내지 못했을 것입니다,,) 
디자인별 접근 …
> [신혜윤] refactor/Week3

- css/index.css
- css/reset.css
- css/sign.css
- index.html
- js/sign.js
- signin.html
- signup.html
로그인/회원가입 페이지
- 입력값이 있는지 확인하는 기능
- 이메일 형식의 값을 입력했는지 확인하는 기능
- 정확한 값을 입력하면 /folder로 이동하는 기능
- 회원가입 시 비밀번호와 확인값이 일치하는지 확인하는 기능
> [김하늘] Week 4

- src/css/reset.css
- src/css/sign.css
- src/css/style.css
- src/folder.html
- src/index.html
- src/sign.js
- src/signin.html
- src/signup.html
- src/style.css
- css 따로 분리했습니다.
- css 네이밍 변경했습니다.
- 주석들 추가 하였습니다.
- 같은 컨테이너 내 class들 css 파일에서 위치 붙어있게 정리했습니다.
- 메타 태그 이미지 url로 변경했습니다.
- 하드코딩으로 gird 내에서 위치 잡던 걸 align, justify로 위치 잡도록 수정했습니다.
- 4주차 과제 진행 완료했습니다.
- flex로 위치를 바꾸어 진행을 하던 도중 아래 그림처럼 바꾸고 싶었는데 text-align으로는 할 수 없었습니다. 방법이 있을까요?
- css 네이밍 하던 도중에 네이밍이 너무 길어지는 거 같아서 이게 맞나 싶었습니다. 아래의 class를 예로 들어서 멘토님은 어떤 식으로 짓는지 궁금합니다.
(ex. header__content_div1_h1_span 이런 길은 애들...)
> [박경서] week4

- pages/folder/index.html
- pages/landing/style.css
- pages/login/login.js
- pages/login/signin.html
- pages/login/signup.html
- pages/login/style.css
- pages/login/login.js 생성
- 유효성 검증 함수 생성
- 에러메세지 생성/출력 함수 생성
- 눈을 감았다 뜸으로 패스워드가 가려지는 기능에 대해서, 저는 css파일에서 class에 따라 이미지의 src를 변경하고, 자바스크립트로 이미지의 alt를 변경했습니다. 더 효율적인 방법이 있을지 궁금합니다.
- validate 함수와 printMessage함수의 구상에 있어서도 더 좋은 방법이 있을지 궁금합니다.
- 효율적으로 함수를 나누고 만들었는지 궁금합니다.
> [강현지] Week4

- index.html
> [week4] 한승주

- assets/css/sign_form.css
- assets/js/sign_form.js
- signin.html
- signup.html
- signin 페이지 이메일, 비밀번호 유효성 검사 기능 추가
- 요구사항대로 구현하는 것에만 집중했습니다. 코드가 간결하지 않은 것 같아 아쉽습니다. (어려워요🥲)
- 이번 코드 리팩토링시 어느 부분 개선에 중점을 두는 것이 좋을지 궁금합니다.
- 스타일 변경의 두 가지 방법 중 어느 것이 더 선호되는지 궁금합니다!
① css에 스타일 작성 후 class 삽입
② JS 내에서 style 속성 사용하기
> [민서영] Week4

- src/assets/css/global.css
- src/pages/account/account.css
- src/pages/account/account.js
- src/pages/account/signin/index.html
- src/pages/account/signin/signin.js
- src/pages/account/signup/index.html
- src/pages/account/signup/signup.js
- src/utils/nodeUtils.js
- 로그인 ,회원가입 페이지 에러 이벤트 및 비밀번호 타입변경 토글이벤트 기능을 추가하였습니다.
- signin , signup js 파일에서 공통으로 사용하는 로직은 account js에 넣어 모듈화 하였습니다.
- 빈칸 체크 
-이메일 유효성 검사
-비밀번호 타입변경 토글 이벤트
-속성을 변경할때 어떤 방식으로 변경하는게 성능상 효율적인지 궁금합니다. HTML안에서 정적으로 변하는 attribute를 통해 변경해야하는 것과 DOM tree 안에있는property를 통해  동적으로 변하는게 어떤 차이가 있는지 명확하게 이해가 되지 않습니다..
-eyes_toggle 이벤트 로직을 작성하면서 sginup 페이지에서는 '비밀번호' ,'비밀번호 확인' 두 요소에서 같은 클래스를 가진 toggle 이벤트가 동작하기 위해서 forEach를 사용해 요소에 이벤트를 주었습니다. 혹시 그외에 방법이 있는지 궁금합니다.
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다. 감사합니다.
> [남궁수영] week4

- signin/folder.html
- signin/index.html
- signin/index.js
- signin/style.css
- [o]이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지가 보이나요?
- [o] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 input에 빨강색 테두리와 아래에 “올바른 이메일 주소가 아닙니다.” 빨강색 에러 메세지가 보이나요?
- [o]  이메일: test@codeit.com, 비밀번호: codeit101 으로 로그인 시도할 경우, “/folder” 페이지로 이동하나요?
- [o]  비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요?
- [o] 이외의 로그인 시도의 경우 이메일, 비밀번호 input에 빨강색 테두리와 각각의 input아래에 “이메일을 확인해주세요.”, “비밀 
번호를 확인해주세요.” 빨강색 에러 메세지가 보이나요?
- [o] 이메일, 비밀번호 input에 에러 관련 디자인을 Components 영역의 에러 케이스로 적용했나요?
- [o] [심화] 눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 하나요?
- [o] [심화] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없 
는 눈 모양 아이콘이 보이나요?
-
-
-
-
> [고민혁] week4

- pages/login/addEvents.js
- pages/login/functions.js
- pages/login/login.js
- pages/login/signin.html
- pages/login/signin.js
- pages/login/signup.html
- pages/login/signup.js
- pages/login/style.css
- pages/login/tags.js
- login.js의 모듈화
- 함수들 리팩토링
- 유효성검사 항목 추가
- 엔터키 이벤트 추가
- 기존 이메일 정규식 변경
- 모듈화를 효율적으로 했는지 궁금합니다.
- 함수들을 전체적으로 역할에 맞게 수정하고 추가했는데 너무 세세하게 나눈것은 아닌지 궁금합니다.
- 회원가입시에만 추가로 필요한 validation이 있어서 focusout함수를 추가했는데 이렇게 작성했을 때 문제점이 있진 않을지 궁금합니다. (같은 이벤트에서 2개의 함수가 호출되는 부분이 괜찮을까요?)
- 클릭이벤트와 엔터키이벤트로 같은 함수를 사용해야해서 onClickSignup, onEnterSignup, signup 이렇게 3개의 함수가 생성되었는데요, onClickSignup과 onEnterSignup의 내용이 거의 비슷하기도 해서 합칠 수 있다거나, 다른 방법이 있었을까 궁금합니다!
> [강현지] Week5 11팀

- js/signIn.js
- js/signUp.js
- js/utils.js
- 함수명 수정 (TryLogin to tryLogin, eyeComponentOnOffChange to changeEyeComponentOnOff, activeError to validateInput)
- utils.js : e.target -> target으로 공통화
- eyeComponents : forEach 메소드 인자명 수정
- trySignUp 함수 분기 처리 관련 코드 수정
<br>
- trySignUp 함수 분기 처리 코드 수정이 적절한 방식으로 이루어졌는지 확인해주시면 감사하겠습니다.
- 함수명 같이 자꾸 비슷한 부분에서 실수가 나오는데, 더 신경쓰겠습니다...
> [김다은] week5 -2

- css/sign.css
- js/sign-test.js
- signin.html
- signup.html
- 함수형 프로그래밍에서 배운 것을 적용하여 리팩토링을 했습니다.
https://weekly-mission-haneul-kim.netlify.app/
- 모듈로 바꾸려면 class Dom에서 locator 함수를 분리해야 할 것 같습니다. variable 객체도 문제가 있을거 같아요
> [김하늘] Week 5

- js/signin.js
- js/signup.js
- js/utils.js
- pages/signin.html
- pages/signup.html
- style/signin.css
[- [x] 비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input에 빨강색 테두리와 아래에 “비밀번호가 일치하지 않아요.” 빨강색 에러 메세지가 보이나요?
- 4주 차 멘토링 반영 (눈 아이콘 div 박스 수정 & script 태그 defer 속성 추가)
- 회원가입 에러 메시지 이벤트 등록
- 회원가입 제출 이벤트 등록
- 정규식을 이용한 이메일과 비밀번호 유효성 검사 기능 추가
- 모듈화를 여러 번 시도했었는데 tag, utils로 나눴다가 DOM 접근을 모듈화할 필요없다는 걸 알고 util만 만들다가 제 코드에서 어떻게 모듈화를 할지 아이디어가 생각나지 않아서 이렇게 제출합니다.
-  모듈화의 기준을 제가 함수 단위로 잡았다가 특정 기능 단위를 기준으로 모듈화해야 하는 걸 늦게 인지했습니다. 
- 예시) 
```js
const checkEmailError = (event) => {
const EMAIL_REGEX = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g;
if (event.target.value === "") {
emailErrorMessage.style.display = "block";
emailErrorMessage.textContent = "이메일을 입력해주세요";
email.classList.add("border-red");
return false;
} else if (!EMAIL_REGEX.test(event.target.value)) {
emailErrorMessage.style.display = "block"; …
```
> [송민혁] week5

- folder.html
- signin.html
- signin.js
- signup.html
- signup.js
- style/index.css
- style/signin.css
- [] [기본] 이메일, 비밀번호, 비밀번호 확인 input에 에러 관련 디자인을 Components 영역의 에러 케이스로 적용했나요?
- [] [심화] 눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 하나요?
- [] [심화] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요?
- [] [심화] 로그인, 회원가입 페이지에 공통적으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용했나요?
-
-
-
-
> Part1 박세은 week5

- scripts/accounts/accountInfo.js
- scripts/accounts/constants.js
- scripts/accounts/validAccount.js
- scripts/constants.js
- scripts/errors/errors.js
- scripts/input/checkPassword.js
- scripts/input/checkSignInEmail.js
- scripts/input/checkSignInPassword.js
- scripts/input/checkSignupEmail.js
- scripts/input/emailRegex.js
- scripts/signin.js
- scripts/signup.js
- scripts/toggleImage.js
- signin.html
- signup.html
- styles/signin.css
-계정 정보가 test@codeit.com / codeit101 외에도 여러 개가 있다고 가정하고 함수를 수정했습니다
-모듈화 진행했으나 방향성이 올바른지 확인 필요합니다ㅠㅠ 
1) 요구사항 중 Enter키 입력으로 회원가입이 되도록 하기 관련 질문입니다
2) 비슷한 코드인데 모듈화를 할 수 있을까요? 조건과 리턴값이 다르므로 파일을 분리하는 게 맞을까요?
3) validAccount.js 파일 >
파일을 별도로 분리하긴 했지만 signin.js 에서만 사용됩니다.. 분리하지 않아야 될까요?
4) 모듈화를 하니 변수 선언을 여기저기서 중복해서 하게 되어서 오히려 복잡하고 코드도 생각보다 줄어들지 않은 것 같아요 ㅠㅠ
어떻게 해야 효율적으로 파일을 분리할 수 있을까요?  변수 선언은 어떻게 해야 할까요?? >>> 이부분이 이번 과제 하면서 큰 고민이었습니다!
> [신혜윤] Refactor/WEEK5

- .vscode/settings.json
- common.css
- pages/sign/modules/constant.js
- pages/sign/modules/functions.js
- pages/sign/modules/localStorage.js
- pages/sign/modules/message.js
- pages/sign/modules/regex.js
- pages/sign/modules/tags.js
- pages/sign/signcommon.css
- pages/sign/signin.html
- pages/sign/signin.js
- pages/sign/signup.html
- pages/sign/signup.js
- 지난주 피드백을 최대한 반영하려고 노력하였습니다.
- 함수를 사용할 수 있는 부분은 최대한 함수를 사용해서 코드를 간소화하려고 노력하였습니다.
- 변수명과 함수명을 카멜케이스로 변경하였습니다.
- 기본, 심화 요구사항을 최대한 구현하였습니다
- async/await를 통해 POST를 보내고 응답을 받아오는 것 까지는 이해 했는데 그 이후의 동작 처리가 적절했는지 궁금합니다.
- LocalStorage와 accessToken을 활용하는 부분은 이후 배우는 내용이라고 해서 일단 구글링을 통해 작동만 하도록 했습니다.
- 잘 모르지만 LocalStorage에 accessToken이 있으면 아예 window.location.href 를 사용해서 folder페이지로 넘겼는데
혹시 이 방법에 문제가 있을까요? 
> [전동훈] Week6 11팀

- folder.html
- js/constants.js
- js/pages/folder.js
- js/pages/index.js
- js/pages/signin.js
- js/pages/signup.js
- js/utils.js
- 마지막 코드 리뷰네요. 그동안 주어진 시간 내에 정말 많은 부분을 알려주셔서 정말 감사했습니다 ☺️
- 요구사항을 모두 구현한 것 같은데, accessToken이 undefined로 나오는 것 같아 이 부분 확인이 필요할 것 같습니다.
- Enter 키 입력 시 submit 시도하는 부분에도 문제가 있는 것 같아 다시 한 번 검토해보겠습니다.
> [주소희] Week 6

- css/index.css
- folder.html
- index.html
- javascript/config/apiurl.js
- javascript/eyeIcon.js
- javascript/main.js
- javascript/member/index.js
- javascript/member/signin.js
- javascript/member/signup.js
- javascript/utils.js
- 
-
로그인
https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/111848336/96a2e6bf-c0f9-4c2c-887c-96f9dd9cf019
로컬스토리지 저장
- 여태까지 남들이 못 알아보는 코드를 작성했었는데 멘토님 덕분에 여러가지 많이 알게 되고 잘 정리된 것 같습니다. (아직 부족하지만 많이 연습해보겠습니다 ㅎㅎ) 감사합니다.
> [남민섭] Week6

- js/signIn.js
- js/signUp.js
- js/utils.js
<br>
- 리펙토링: 분기 처리 함수 추가
- 항상 자세하게 설명해주셔서 코드를 수정하는 데 큰 도움이 되었습니다. 마지막 PR도 잘 부탁드립니다. 감사합니다!
> [김다은] week6

- .gitignore
- config/index.js
- js/user/login.js
- js/user/signup.js
- js/user/user.js
 (중복된 이메일 확인은 “[test@codeit.com](mailto:test@codeit.com)”을 활용해 주세요.)
- 로그인, 회원가입, 이메일 중복 체크 api 연동
- 5주차 피드백 반영
> [전수빈] week6

- index.html
- src/scripts/api.js
- src/scripts/checkEventType.js
- src/scripts/checkToken.js
- src/scripts/constants.js
- src/scripts/errorMsg.js
- src/scripts/signin.js
- src/scripts/signup.js
- src/scripts/toggleEye.js
- src/scripts/validations.js
- [코드리뷰 반영] js파일의 몇몇 함수들과 변수를 리팩토링하였습니다.
- signin, signup.js 파일에서 각각 선언하였던 상수들을 constants.js로 분리하여 같이 쓸 수 있도록 하였습니다.
[🔎 여기서 확인해주세요✨](https://hw-weekly-01.netlify.app/)
- 로그인/회원가입에 성공하면 다음과 같은 folder 페이지로 넘어갑니다.
- 제가 느끼기에는 다른 일반적인 페이지들보다 응답 속도가 느린 것 같습니다. 제가 js파일 구조를 잘못짰거나 로직에 문제가 있어서 그런걸까요..? 오히려 여러 js파일을 불러오는게 속도가 느려진다는 것을 보고 signup.js와 signin.js 파일에서 필요한 모듈을 불러오고 이벤트 핸들러를 처리하도록 구성하였는데 뭐가 문제인지 모르겠습니다,,
- 가벼운 커밋 관련 질문입니다! 이번주 미션이 기존에 string 상수를 가지고 직접 비교하던 방식에서 POST 요청 방식으로 바꾸는 것인데,, 홈페이지 입장에서 보면 이게 새로운 기능을 추가(feat)한 것인지 잘 모르겠습니다,, 멘토님이라면 지금 이 커밋들을 feat으로 하실 것인지, refactor로 하실 것인지 궁금합니다!
- 다른 분 PR을 보면서 어떤 멘토님께서 “변수의 스코프를 적게 가져갈수록 좋다”고 하신 걸 봤는데요! 저는 지금 방식이 거의 로컬 변수(html에서 불러오는 변수들 기준)는 사용하지 않고, constants.js 모듈에서 불러와서 전역 변수로 사용하는 방식인데.. 같은 변수를 여러 번 선언하더라도 로컬 변수로 사용하는 게 더 좋나요?
- 실무에서는 axios …
> [안희원] Week6

- 1-Weekly-Mission/folder.html
- 1-Weekly-Mission/js/api.js
- 1-Weekly-Mission/js/index.js
- 1-Weekly-Mission/js/signin.js
- 1-Weekly-Mission/js/signup.js
- 1-Weekly-Mission/signin.html
- 1-Weekly-Mission/signup.html
> [김나은] week6

- folder.html
- js/constants.js
- js/pages/signin.js
- js/pages/signup.js
- js/utils.js
- 멘토님 덕분에 많은 것을 알게 되었고 어떻게 공부해야 할지에 대해서도 정말 많이 알게 되었습니다. 감사합니다!!
> [이규호] week6

- api/post.js
- constants/error-message.js
- constants/selector.js
- sign/signin/index.html
- sign/signin/index.js
- sign/signup/index.html
- sign/signup/index.js
- sign/style.css
- utils/error.js
- utils/toggle-icon.js
- utils/validation.js
 
- 지난주 과제 리팩토링
- 에러메세지 모듈화
- 로그인 API 추가
- 회원가입 API 추가
- 6주 동안 고생 많으셨어요!! 정말 많이 배웠어요!! 감사합니다!! 
- 심화 부분은 해결하지 못했습니다.. 마지막은 다 해내는 모습 보여드리고 싶었는데 아직은 많이 부족하네요 ㅠㅠ 
> [김소은] week6
